language: ruby
sude: false
cache: bundler
before_install:
  - gem update --system # use the very latest Rubygems
  - gem install bundler # use the very latest Bundler
script:
  - bundle exec rake test
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
  - gemfiles/rails6.0.gemfile
  - gemfiles/rails6.1.gemfile
matrix:
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/rails6.0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails6.0.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails6.1.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails6.1.gemfile
notifications:
  email:
    on_success: always
    on_failure: always
